files:
  include: 'html/scss/*.scss'
rules:
  force-element-nesting: 0
  nesting-depth:
    - 1
    - max-depth: 4
  no-css-comments: 0
  no-ids: 0
  no-important: 0
  no-transition-all: 0
  no-url-domains: 0
  no-url-protocols: 0
  no-qualifying-elements:
    - 1
    - allow-element-with-class: true
  no-vendor-prefixes: 0
  property-sort-order: 0